// // export const SET_MOVIES_SUCCESS = 'SET_MOVIES_SUCCESS'
// export const SET_MOVIES_SUCCESS = 'SET_MOVIES_SUCCESS'
// export const SET_MOVIES_ERROR = 'SET_MOVIES_ERROR'

export enum ActionType {
  SET_MOVIES_SUCCESS = 'SET_MOVIES_SUCCESS',
  SET_MOVIES_ERROR = 'SET_MOVIES_ERROR',
  SET_DETAILS = 'SET_DETAILS'
}
