// // export const SET_MOVIES_SUCCESS = 'SET_MOVIES_SUCCESS'
// export const SET_MOVIES_SUCCESS = 'SET_MOVIES_SUCCESS'
// export const SET_MOVIES_ERROR = 'SET_MOVIES_ERROR'

export enum ActionType {
  CLEAR_ALERT = 'CLEAR_ALERT',
  CHANGE_THEME = 'CHANGE_THEME',
  GET_NOW_PLAYING_BEGIN = 'GET_NOW_PLAYING_BEGIN',
  GET_NOW_PLAYING_SUCCESS = 'GET_NOW_PLAYING_SUCCESS',
  GET_NOW_PLAYING_ERROR = 'GET_NOW_PLAYING_ERROR',
  SET_MOVIES_SUCCESS = 'SET_MOVIES_SUCCESS',
  SET_MOVIES_ERROR = 'SET_MOVIES_ERROR',
  SET_DETAILS = 'SET_DETAILS',
  MODE_NOW_PLAYING = 'MODE_NOW_PLAYING',
  SET_SEARCH_MODE = 'SET_SEARCH_MODE',
  SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS',
  SET_WATCHLIST_MODE = 'SET_WATCHLIST_MODE',
  ADD_TO_WATCHLIST = 'ADD_TO_WATCHLIST',
  REMOVE_FROM_WATCHLIST = 'REMOVE_FROM_WATCHLIST',
  GET_REVIEWS_BEGIN = 'GET_REVIEWS_BEGIN',
  GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS',
  GET_REVIEWS_ERROR = 'GET_REVIEWS_ERROR',
  HIDE_REVIEWS = 'HIDE_REVIEWS'
}
