// // export const SET_MOVIES_SUCCESS = 'SET_MOVIES_SUCCESS'
// export const SET_MOVIES_SUCCESS = 'SET_MOVIES_SUCCESS'
// export const SET_MOVIES_ERROR = 'SET_MOVIES_ERROR'

export enum ActionType {
  SET_MOVIES_SUCCESS = 'SET_MOVIES_SUCCESS',
  SET_MOVIES_ERROR = 'SET_MOVIES_ERROR',
  SET_DETAILS = 'SET_DETAILS',
  GET_NOW_PLAYING = 'GET_NOW_PLAYING',
  SET_SEARCH_MODE = 'SET_SEARCH_MODE',
  SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS',
  SET_WATCHLIST_MODE = 'SET_WATCHLIST_MODE'
}
